# moonfly theme for WezTerm
#
# Upstream: github.com/bluz71/vim-moonfly-colors
#
# Usage: copy this theme into the colors directory and then select the moonfly
# 'color_scheme' in your 'wezterm.lua' configuration.

[metadata]
name = "moonfly"
origin_url = "https://github.com/bluz71/vim-moonfly-colors"

[colors]
background = "#080808"
foreground = "#bdbdbd"
cursor_bg = "#9e9e9e"
cursor_fg = "#080808"
cursor_border = "#9e9e9e"
selection_bg = "#b2ceee"
selection_fg = "#080808"
scrollbar_thumb = "#9e9e9e"
split = "#9e9e9e"

ansi = [
  "#323437",
  "#ff5454",
  "#8cc85f",
  "#e3c78a",
  "#80a0ff",
  "#cf87e8",
  "#79dac8",
  "#c6c6c6",
]
brights = [
  "#949494",
  "#ff5189",
  "#36c692",
  "#c6c684",
  "#74b2ff",
  "#ae81ff",
  "#85dc85",
  "#e4e4e4",
]

compose_cursor = "#e3c78a"
visual_bell = "#e3c78a"
